# Generated by Django 4.2.4 on 2023-10-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_education_experience_alter_userprofile_picture'),
        ('blog', '0003_comment_author_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_dislike', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_like', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
